name: megatunix 
adopt-info: megatunix 
summary: MegaTunix Tuning software for MegaSquirt EFI Controllers
description: |
  MegaTunix is a tuning application for Linux, Mac OS-X, other Unix variants and Windows XP/Vista/7 32 bit variants. 
  It supports some of the available DIY EFI Fuel injection solutions including many MegaSquirt products and LibreEMS. 
  It's written in C using the GTK windowing toolkit and is licensed under GPL V2.

grade: stable 
confinement: strict 

architectures:
  - build-on: amd64

apps:
  megatunix:
    command: desktop-launch $SNAP/bin/megatunix
#    desktop: share/applications/megatunix.desktop
    plugs:
      - network
      - network-bind
      - home
      - unity7
      - x11
      - optical-drive
      - removable-media
      - raw-usb
      
parts:
  megatunix:
    plugin: nil
    source: https://github.com/djandruczyk/MegaTunix
    source-type: git
    after: [desktop-gtk2]
    
    override-build: |
      ./autogen.sh
      make
            
    build-packages:
      - libgtkglext1
      - libglade2-dev
      - libtool-bin
      - intltool
      - flex
      - bison
      - libgtkgl2.0-dev
      - libglu1-mesa-dev
      
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
      
    stage-packages:
      - libgtkglext1
      - libglade2-dev
      - libtool-bin
      - intltool
      - flex
      - bison
      - libgtkgl2.0-dev
      - libglu1-mesa-dev    
