name: megatunix # you probably want to 'snapcraft register <name>'
version: '0.5+git' # just for humans, typically '1.2+git' or '1.3.2'
summary: MegaTunix Tuning software for MegaSquirt EFI Controllers # 79 char long summary
description: |
  MegaTunix is a tuning application for Linux, Mac OS-X, other Unix variants and Windows XP/Vista/7 32 bit variants. It supports some of the available DIY EFI Fuel injection solutions including many MegaSquirt products and LibreEMS. It's written in C using the GTK windowing toolkit and is licensed under GPL V2.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  megatunix:
    command: desktop-launch $SNAP/bin/megatunix
    desktop: share/applications/megatunix.desktop
    plugs:
      - home
      - unity7
      - x11
      - removable-media
      - raw-usb
    

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: autotools
    source: https://github.com/djandruczyk/MegaTunix
    source-type: git
    after: [desktop-gtk2]
    build-packages:
      - libgtkglext1
      - libglade2-dev
      - libtool-bin
      - intltool
      - flex
      - bison
      - libgtkgl2.0-dev
    
    # need proper scriplet here. Perhaps a bash script.
    install: |  
      cd bin
      sudo make install
      sudo ldconfig
     
      
